name = "Tlp's 1.21 Slop"
author = "Panda"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c23a0e0bd4a75781c01a2dd467e4d618c6061d5800ed372e86f2971ed7724157"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.2.7"
