name = "Tlp's 1.21 Slop"
author = "Panda"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d3f5557f0ca6bd9865d26586b1d7e148be99068e779b40b58d4c018bdff1f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.2.7"
