name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76b889537a6a4cbf5d576c2bd1943441a1d681d6817598f3e01e1333022ed7da"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
