name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0316e8de9aac5143160b8f64f5da2a8cf745d595a706735011b01d119988fe99"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
