name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4052b13d656ba6e8c84a874f49c27e4ffcbe9db7d1c936fb88ea843dbed7cbaf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
