name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62bb96cb9cc724653fa38e83bbe79ce85e775d6c384a7b5f1b538e91ba5dae0c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
