#Display a message if Patchouli is not installed when joining the game
patchouliWarning = true
#Items that will prevent Thigh Highs from rendering
thighHighsRestrictors = []
#Items that will prevent Hand Warmers from rendering
handWarmersRestrictors = []
#Items that will prevent Pants from rendering
pantsRestrictors = []
#Items that will prevent Shirt from rendering
shirtRestrictors = ["weaversparadise:astolfo_armor_chestplate", "weaversparadise:bridget_armor_jacket", "weaversparadise:felix_armor_jacket"]
#Items that will prevent Choker and it's trinkets from rendering
chokerRestrictors = ["weaversparadise:felix_armor_jacket"]
