name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7d380f05cf6320db1757a1c9cc8a93c0acadcd1242b9210b0bb74c4bef9dfe0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
