name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "840901dd27e711e27c63d6b1df7711a84c83489dcc4b6e4dca17e5d988747ba8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
