name = "Blawg & Artifice 2"
author = "Tlp"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b002e74ffe50b1f52bd2afea631a471b9a402f2689fb1092844902fc915e5ee0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
