name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc8bbbbb059d10cc8f9f17b23385ea179f1d2d43a2fe6035f5835c97d5b3d31b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
