name = "Scrim3ers"
author = "Tlp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f917251d9b4b7f01336030cb1adf984f57e7524899a97c8ff5089c90a1ee4a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
